### ISSUE TITLE
Engelsk versjon

### ISSUE THREAD

**Issue by askaret** [bouvet/sikkerhet.bouvet.no#81]
Trenger engelsk oversettelse av all content

**Comment by chrish** [comment]
Har begynt såvidt å oversette, ref egen fork

**Comment by chrish** [comment]
[Ref PR 103](https://github.com/bouvet/sikkerhet.bouvet.no/pull/103)

**Comment by chrish** [comment]
Lukker, gammel sak. Alt innhold finnes på engelsk.
