### ISSUE TITLE
Fysisk sikring

### ISSUE THREAD

**Issue by askaret** [bouvet/sikkerhet.bouvet.no#93]

**Comment by mikael-kalstad** [comment]
Ikke noe artikkel, men kan kanskje være til inspirasjon for innhold? 
Har sett et par videoer fra denne fyren tidligere og ble overrasket over hvor enkelt det var å komme seg inn i mange tilfeller.

Link til video: https://www.youtube.com/watch?v=VJ4FDOw9NcI
